---
inventory:
    plugin: nornir.plugins.inventory.simple.SimpleInventory
    options:
        host_file: "handling_connections/example2/inventory/hosts.yaml"
        group_file: "handling_connections/example2/inventory/groups.yaml"

