---
inventory: nornir.plugins.inventory.simple.SimpleInventory
SimpleInventory:
    host_file: "handling_connections/example1/inventory/hosts.yaml"
    group_file: "handling_connections/example1/inventory/groups.yaml"

